[
  "promotions": [
    {
      "id": 1,
      "website": "http://www.audiosf.com",
      "address": "316 11th Street",
      "city": "San Francisco",
      "state": "CA",
      "zip": "94103",
      "phoneNumber": "415-481-0556",
      "totalRewards": "1000",
      "incentives": "null",
      "ethWalletAddress": "0x50Ebe9ad50DCf1Be1A35570E29587fa9F6eCDB46",
      "startTime": "10PM",
      "endTime": "2AM",
      "email": "reservations@audiosf.com",
      "eventDate": "01/13/2018",
      "eventName": "Oliver Nelson",
      "venueName": "Audio SF",
      "flyerUrl": "../../public/images/concert-flyer-01.jpg"
    },
    {
      "id": 2,
      "website": "http://www.audiosf.com",
      "address": "316 11th Street",
      "city": "San Francisco",
      "state": "CA",
      "zip": "94103",
      "phoneNumber": "415-481-0556",
      "totalRewards": "1000",
      "incentives": "null",
      "ethWalletAddress": "0x50Ebe9ad50DCf1Be1A35570E29587fa9F6eCDB46",
      "startTime": "10PM",
      "endTime": "2AM",
      "email": "reservations@audiosf.com",
      "eventDate": "01/19/2018",
      "eventName": "Ardalan",
      "venueName": "Audio SF",
      "flyerUrl": "../../public/images/concert-flyer-02.jpg"
    },
    {
      "id": 3,
      "website": "http://www.audiosf.com",
      "address": "316 11th Street",
      "city": "San Francisco",
      "state": "CA",
      "zip": "94103",
      "phoneNumber": "415-481-0556",
      "totalRewards": "1000",
      "incentives": "null",
      "ethWalletAddress": "0x50Ebe9ad50DCf1Be1A35570E29587fa9F6eCDB46",
      "startTime": "10PM",
      "endTime": "2AM",
      "email": "reservations@audiosf.com",
      "eventDate": "02/09/2018",
      "eventName": "Chris Lake",
      "venueName": "Audio SF",
      "flyerUrl": "../../public/images/concert-flyer-03.jpg"
    },
    {
      "id": 4,
      "website": "http://www.audiosf.com",
      "address": "316 11th Street",
      "city": "San Francisco",
      "state": "CA",
      "zip": "94103",
      "phoneNumber": "415-481-0556",
      "totalRewards": "1000",
      "incentives": "null",
      "ethWalletAddress": "0x50Ebe9ad50DCf1Be1A35570E29587fa9F6eCDB46",
      "startTime": "10PM",
      "endTime": "2AM",
      "email": "reservations@audiosf.com",
      "eventDate": "02/15/2018",
      "eventName": "Volac",
      "venueName": "Audio SF",
      "flyerUrl": "../../public/images/concert-flyer-04.jpg"
    },
    {
      "id": 5,
      "website": "http://www.audiosf.com",
      "address": "316 11th Street",
      "city": "San Francisco",
      "state": "CA",
      "zip": "94103",
      "phoneNumber": "415-481-0556",
      "totalRewards": "1000",
      "incentives": "null",
      "ethWalletAddress": "0x50Ebe9ad50DCf1Be1A35570E29587fa9F6eCDB46",
      "startTime": "10PM",
      "endTime": "2AM",
      "email": "reservations@audiosf.com",
      "eventDate": "03/02/2018",
      "eventName": "Mark Knight",
      "venueName": "Audio SF",
      "flyerUrl": "../../public/images/concert-flyer-05.jpg"
    },
    {
      "id": 6,
      "website": "http://www.audiosf.com",
      "address": "316 11th Street",
      "city": "San Francisco",
      "state": "CA",
      "zip": "94103",
      "phoneNumber": "415-481-0556",
      "totalRewards": "1000",
      "incentives": "null",
      "ethWalletAddress": "0x50Ebe9ad50DCf1Be1A35570E29587fa9F6eCDB46",
      "startTime": "10PM",
      "endTime": "2AM",
      "email": "reservations@audiosf.com",
      "eventDate": "02/02/2018",
      "eventName": "DJ Destructo",
      "venueName": "Audio SF",
      "flyerUrl": "../../public/images/concert-flyer-06.jpg"
    },
    {
      "id": 7,
      "website": "http://www.audiosf.com",
      "address": "316 11th Street",
      "city": "San Francisco",
      "state": "CA",
      "zip": "94103",
      "phoneNumber": "415-481-0556",
      "totalRewards": "1000",
      "incentives": "null",
      "ethWalletAddress": "0x50Ebe9ad50DCf1Be1A35570E29587fa9F6eCDB46",
      "startTime": "10PM",
      "endTime": "2AM",
      "email": "reservations@audiosf.com",
      "eventDate": "01/19/2018",
      "eventName": "Belly Kenny",
      "venueName": "Audio SF",
      "flyerUrl": "../../public/images/concert-flyer-07.jpg"
    },
    {
      "id": 8,
      "website": "http://www.audiosf.com",
      "address": "316 11th Street",
      "city": "San Francisco",
      "state": "CA",
      "zip": "94103",
      "phoneNumber": "415-481-0556",
      "totalRewards": "1000",
      "incentives": "null",
      "ethWalletAddress": "0x50Ebe9ad50DCf1Be1A35570E29587fa9F6eCDB46",
      "startTime": "10PM",
      "endTime": "2AM",
      "email": "reservations@audiosf.com",
      "eventDate": "01/19/2018",
      "eventName": "Break Bot",
      "venueName": "Audio SF",
      "flyerUrl": "../../public/images/concert-flyer-08.jpg"
    },
    {
      "id": 9,
      "website": "http://www.audiosf.com",
      "address": "316 11th Street",
      "city": "San Francisco",
      "state": "CA",
      "zip": "94103",
      "phoneNumber": "415-481-0556",
      "totalRewards": "1000",
      "incentives": "null",
      "ethWalletAddress": "0x50Ebe9ad50DCf1Be1A35570E29587fa9F6eCDB46",
      "startTime": "10PM",
      "endTime": "2AM",
      "email": "reservations@audiosf.com",
      "eventDate": "01/19/2018",
      "eventName": "Satin Jacket",
      "venueName": "Audio SF",
      "flyerUrl": "../../public/images/concert-flyer-09.jpg"
    },
    {
      "id": 10,
      "website": "http://www.audiosf.com",
      "address": "316 11th Street",
      "city": "San Francisco",
      "state": "CA",
      "zip": "94103",
      "phoneNumber": "415-481-0556",
      "totalRewards": "1000",
      "incentives": "null",
      "ethWalletAddress": "0x50Ebe9ad50DCf1Be1A35570E29587fa9F6eCDB46",
      "startTime": "10PM",
      "endTime": "2AM",
      "email": "reservations@audiosf.com",
      "eventDate": "01/19/2018",
      "eventName": "Neon Indian",
      "venueName": "Audio SF",
      "flyerUrl": "../../public/images/concert-flyer-10.jpg"
    },
    {
      "id": 11,
      "website": "http://www.audiosf.com",
      "address": "316 11th Street",
      "city": "San Francisco",
      "state": "CA",
      "zip": "94103",
      "phoneNumber": "415-481-0556",
      "totalRewards": "1000",
      "incentives": "null",
      "ethWalletAddress": "0x50Ebe9ad50DCf1Be1A35570E29587fa9F6eCDB46",
      "startTime": "10PM",
      "endTime": "2AM",
      "email": "reservations@audiosf.com",
      "eventDate": "01/19/2018",
      "eventName": "Eric Morillo",
      "venueName": "Audio SF",
      "flyerUrl": "../../public/images/concert-flyer-11.jpg"
    }
]
